# Generated by Django 5.1.4 on 2025-02-22 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='c_and_a_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reorder_level',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reorder_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier_rate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='update_unit_cost',
        ),
        migrations.AddField(
            model_name='product',
            name='sold_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='total_stock_added',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='total_stock_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.PositiveIntegerField()),
                ('selling_price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_sale_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('sold_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_added', models.PositiveIntegerField()),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('restocked_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
    ]
