# Generated by Django 5.1.4 on 2025-02-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_remove_product_c_and_a_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
