# Generated by Django 5.1.4 on 2025-03-07 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_restockhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pin_code', models.CharField(max_length=6)),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_period', models.IntegerField(help_text='Credit period in days')),
                ('area', models.CharField(max_length=255)),
                ('route', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(default='India', max_length=50)),
                ('tin_no', models.CharField(blank=True, max_length=15, null=True)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('dl_no', models.CharField(blank=True, max_length=20, null=True)),
                ('salesman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.salesman')),
            ],
        ),
    ]
