# Generated by Django 5.1.4 on 2025-03-07 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_customer_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('beneficiary_name', models.CharField(max_length=255)),
                ('ifsc_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_account',
            field=models.ForeignKey(default=2343, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='Product.bankaccount'),
            preserve_default=False,
        ),
    ]
