# Generated by Django 5.1.4 on 2025-03-11 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_alter_customer_address_alter_customer_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('bill_no', models.AutoField(primary_key=True, serialize=False)),
                ('bill_date', models.DateField(auto_now_add=True)),
                ('invoice_no', models.IntegerField(unique=True)),
                ('invoice_date', models.DateField()),
                ('cashier', models.CharField(blank=True, max_length=100, null=True)),
                ('is_local', models.BooleanField(default=True)),
                ('is_interstate', models.BooleanField(default=False)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('hsn_code', models.CharField(max_length=50)),
                ('batch', models.CharField(blank=True, max_length=50, null=True)),
                ('exp_date', models.DateField(blank=True, null=True)),
                ('unit', models.CharField(max_length=50)),
                ('qty', models.PositiveIntegerField()),
                ('free', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.FloatField(default=0)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_percentage', models.FloatField(default=0)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Product.salesinvoice')),
            ],
        ),
    ]
