# Generated by Django 5.1.4 on 2025-03-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_salesinvoice_salesitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
