# Generated by Django 5.1.4 on 2025-03-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0012_salesinvoice_customer_alter_salesinvoice_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
