# Generated by Django 5.1.4 on 2025-03-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0013_supplier_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
