# Generated by Django 5.1.4 on 2025-03-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_alter_salesinvoice_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitem',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
