# Generated by Django 5.1.4 on 2025-03-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0015_alter_salesitem_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='billing_type',
            field=models.CharField(choices=[('wholesale', 'Wholesale'), ('retail', 'Retail'), ('mrp', 'MRP')], default='mrp', max_length=20),
        ),
    ]
