# Generated by Django 5.1.4 on 2025-03-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0016_salesinvoice_billing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casheir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ph_number', models.CharField(max_length=100)),
            ],
        ),
    ]
