# Generated by Django 5.1.4 on 2025-03-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0017_casheir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reorder_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
