# Generated by Django 5.1.4 on 2025-08-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0019_cashier_delete_casheir_alter_salesitem_tax_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='gst_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='round_off',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='cashier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
