# Generated by Django 5.1.4 on 2025-08-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0020_salesinvoice_grand_total_salesinvoice_gst_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
