# Generated by Django 5.1.7 on 2025-09-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0021_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='retail_margin',
            field=models.DecimalField(decimal_places=2, default=80.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tax',
            name='wholesale_margin',
            field=models.DecimalField(decimal_places=2, default=70.0, max_digits=5),
        ),
    ]
